version: '3'

services:  
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: matcha
      MYSQL_USER : matcha
      MYSQL_PASSWORD : password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:    
    image: adminer
    restart: always  
    ports:      
      - "8080:8080"

  backend:
    build: .
    working_dir: /app
    command: "python3 ./app.py"
    restart: always
    ports: 
      - "5000:5000"
    depends_on:
      - database
    volumes: 
      - ./:/app
